backend:
  name: github
  repo: AlexMardanov/gatsby-netlify-cms
  branch: master

media_folder: 'static/uploads'
public_folder: '/uploads'

display_url: https://your-site.com

collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Блог' # Used in the UI
    description: 'Страницы блога'
    folder: 'src/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    # slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: slug
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'page' # Used in routes, e.g., /admin/collections/blog
    label: 'Page' # Used in the UI
    folder: 'src/content/pages' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
